spring:
  datasource:
    url: jdbc:postgresql://pg:5432/studs
    username: s335061
    password: vRIJUF5LsOfG00si
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.yandex.ru
    port: 465
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

server:
  port: 8081

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day